### ISSUE TITLE
TTL Bug (not sure if it's fixable)

### ISSUE THREAD

**Issue by MagesticChicen** [DevAndromeda/quickmongo#53]
Best way to explain the bug is with an example:
So if I ran 
`await db.set("yes.notok", "notok")`
`await db.set("yes.ok", "ok", 5)`
After 5 seconds the entire yes document would be deleted not the ok value from the object. Logically it should only delete the ok value from the object, although I am not sure if this is actually possible with mongo. A bug nonetheless

**Comment by DevAndromeda** [comment]
ttl applies to the whole document, not individual props

**Comment by MagesticChicen** [comment]
Is there a way to make it apply to the properties or is this just a limitation of mongodb

**Comment by DevAndromeda** [comment]
According to mongodb docs, **TTL indexes are special single-field indexes that MongoDB can use to automatically remove documents from a collection after a certain amount of time or at a specific clock time.**

If you need to handle objects inside a document, you would have to implement that yourself. The ttl feature only applies to the document.

**Comment by MagesticChicen** [comment]
Maybe ill submit a feature request or something
The only reason I want TTL within a document is because it is so robust (if your server crashes when a document expires, the document is still removed when back online)
